version: '3.8'

services:
  app:
    image: tot-wissem-main:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/tot

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ep-square-mountain-a5gkd1ts.us-east-2.aws.neon.tech
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: gK5M9SfZlnyL
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database between container restarts

volumes:
  postgres_data:
